[package]
name = "prisma_core_challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
prettytable = "0.10.0"
serde = { version = "1.0", features = ["derive"] }

[lib]
name = "prisma_core_challenge"
path = "src/lib.rs"
